AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket policy'

Parameters:
  S3BucketName:
    Type: String

Resources:
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3BucketName
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - ec2.amazonaws.com
            Action:
              - s3:GetObject
            Resource:  !Sub 'arn:${AWS::Partition}:s3:::${S3BucketName}/*'